ALTER TABLE external_alerts ADD COLUMN IF NOT EXISTS magnitude NUMERIC(4,1);
ALTER TABLE external_alerts ADD COLUMN IF NOT EXISTS lat NUMERIC(8,5);
ALTER TABLE external_alerts ADD COLUMN IF NOT EXISTS lng NUMERIC(8,5);
