/**
 * lib/agents/cron-capability-registry.ts — ЗАМОРОЖЕННЫЙ перечень возможностей.
 *
 * Что здесь лежит: для каждого эндпоинта под `/api/cron/` — что он умеет,
 * снятое переписью `scripts/cron-capability-census.ts` (обход собственных
 * импортов на глубину 2). Не оценка «безопасен ли», а ответ на вопрос «что он
 * может сделать»: пишет ли в базу, ходит ли наружу, шлёт ли людям сообщения,
 * зовёт ли модель, касается ли денег и персональных данных.
 *
 * ── Зачем морозить ─────────────────────────────────────────────────────────
 *
 * Возможность появляется тихо. Роут-перепись, объявленная read-only, получает
 * одну строку `UPDATE` — и в диффе это выглядит как обычная правка в файле,
 * который «и так про базу». Роут диагностики обзаводится вызовом модели и
 * начинает жечь токены по расписанию. Замороженный перечень делает такое
 * появление ВИДИМЫМ: сторож `tests/unit/cron-capability-frozen.test.ts`
 * краснеет, пока новая возможность не внесена сюда осознанно.
 *
 * Тот же приём, что у `UNDECLARED_TABLES` и у реестра LLM-хостов (§8, D2), и по
 * той же причине: запретить рост беды дешевле, чем разом убрать накопленное.
 *
 * ── Как обновлять ──────────────────────────────────────────────────────────
 *
 *   npx tsx scripts/cron-capability-census.ts --freeze
 *
 * Обновлять — ТЕМ ЖЕ коммитом, которым добавлена возможность, и с причиной в
 * сообщении. Обновление отдельным «привёл реестр в порядок» коммитом лишает
 * заморозку смысла: именно момент появления и надо было увидеть.
 *
 * ЧЕГО ЗДЕСЬ НЕТ. Перечень собран статикой и знает границы: динамический
 * `await import()` и всё за пределом глубины обхода в него не попадают.
 * Перепись честно возвращает такие модули полем `unexplored` — «не знаю» не
 * складывается с «не умеет» (§4.0). Судить по этому файлу, что роут чего-то НЕ
 * умеет, нельзя; можно судить, что перечень его умений ИЗМЕНИЛСЯ.
 */
import type { Capability } from '@/lib/agents/cron-capabilities';

export const CRON_CAPABILITIES: Record<string, readonly Capability[]> = {
  'abandoned-bookings': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'ai-channel-check': ['net_out', 'telegram', 'pd_direct'],
  'ai-models': ['db_read', 'db_write', 'net_out', 'ai'],
  'alerts-census': ['db_read', 'db_write', 'net_out'],
  'anthropic-path-probe': ['net_out'],
  'backfill-partner-profile': ['db_read', 'db_write'],
  'backfill-place-images': ['db_read', 'db_write', 'net_out', 'ai'],
  'beacon-check': ['db_read', 'db_write'],
  'booking-attempts': ['db_read'],
  'booking-stall-alert': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'catalog-census': ['db_read'],
  'catalog-diag': ['db_read'],
  'channel-photo-check': ['db_read'],
  'channel-post': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'channel-post-tour': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'channel-readiness': ['db_read', 'pd_direct'],
  'channel-sync': ['db_read', 'db_write'],
  'checkin-watchdog': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'commission-dry-run': ['db_read', 'db_write', 'money'],
  'danger-analysis': ['db_read', 'db_write', 'net_out', 'ai'],
  'data-inventory': ['db_read', 'db_write'],
  'data-repair': ['db_read', 'db_write', 'net_out'],
  'deepseek-model-probe': ['db_read', 'db_write', 'net_out', 'ai'],
  'dem-elevations': ['db_read', 'db_write'],
  'db-size-census': ['db_read'],
  'digest': ['db_read', 'db_write', 'net_out', 'telegram', 'ai', 'money', 'pd_direct'],
  'document-expiry': ['db_read', 'db_write', 'net_out', 'telegram'],
  'duplicate-routes-audit': ['db_read', 'db_write'],
  'eco-expire': ['db_read', 'db_write'],
  'editor': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'editor-eval': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'editor-job': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'editor-result': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'elevation-backfill': ['db_read'],
  'engagement': ['db_read', 'db_write', 'net_out', 'telegram'],
  'enrich-passports': ['db_read', 'db_write', 'net_out', 'ai'],
  'enrich-routes': ['db_read', 'db_write', 'net_out', 'ai'],
  'evo': ['db_read', 'db_write', 'net_out', 'telegram', 'ai', 'pd_direct'],
  'evo-apply': ['db_read', 'db_write'],
  'evo-findings': ['db_read', 'db_write', 'net_out'],
  'evo-issues': ['db_read'],
  'evo-log-cleanup': ['db_read', 'db_write'],
  'evo-report': ['db_read', 'db_write', 'net_out'],
  'evo-review-job': ['db_read', 'db_write', 'net_out'],
  'explain-availability': ['db_read'],
  'field-check-photo': ['db_read'],
  'field-check-queue': ['db_read'],
  'followups': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'funnel-census': ['db_read', 'db_write', 'net_out'],
  'group-scout': ['db_read', 'db_write', 'net_out', 'ai'],
  'health': ['db_read', 'db_write', 'net_out', 'telegram', 'ai', 'money', 'pd_direct'],
  'hidden-tracks-census': ['db_read'],
  'import-route-passports': ['db_read', 'db_write', 'net_out', 'ai', 'pd_direct'],
  'import-routes': ['db_read', 'db_write', 'net_out'],
  'industry-intel': ['db_read', 'db_write', 'ai'],
  'inspect-tour-card': ['db_read', 'pd_direct'],
  'intel-feeds-census': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'intel-note': ['db_read', 'db_write'],
  'intelligence': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'kb-gap': ['db_read', 'db_write', 'net_out', 'ai'],
  'images-to-s3': ['db_read', 'db_write', 'net_out'],
  'images-oversize': ['db_read', 'db_write'],
  'kernel-worker': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'kml-inbox': ['db_read', 'db_write'],
  'kuzmich': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'kuzmich-eval': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'kuzmich-places': ['db_read', 'db_write', 'net_out', 'ai'],
  'kuzmich-redteam': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'kvert-acc': ['db_read', 'db_write', 'net_out'],
  'leads-followup': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'leads-process': ['db_read', 'db_write', 'net_out', 'ai', 'pd_direct'],
  'legacy-tours-census': ['db_read'],
  'legacy-tours-cleanup': ['db_write'],
  'legislation-sync': ['db_read', 'db_write', 'net_out', 'ai'],
  'llm-budget-check': ['db_read', 'db_write', 'net_out', 'telegram'],
  'locked-out-partners': ['db_read'],
  'max-webhook': ['net_out'],
  'memory-contradiction': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'memory-reflect': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'ocr-passports': ['db_read', 'db_write', 'net_out'],
  'ocr-passports-pending': ['db_read', 'net_out'],
  'ocr-passports-write': ['db_read', 'db_write'],
  'operator-reach': ['db_read', 'pd_direct'],
  'operator-site-audit': ['db_read', 'db_write', 'net_out'],
  'osm-import': ['db_read', 'db_write', 'net_out'],
  'osm-traces': ['db_read', 'db_write', 'net_out', 'telegram'],
  'partner-candidates-census': ['db_read', 'pd_direct'],
  'partner-cleanup': ['db_read', 'db_write'],
  'partner-junk-census': ['db_read', 'db_write', 'net_out'],
  'passport-flag-census': ['db_read', 'pd_direct'],
  'payment-config': [],
  'payment-test-setup': ['db_read', 'db_write', 'money'],
  'payouts': ['db_read', 'db_write', 'net_out', 'telegram', 'money', 'pd_direct'],
  'place-activity-census': ['db_read'],
  'place-audit': ['db_read'],
  'place-coords': ['db_read', 'db_write'],
  'place-link': ['db_read', 'db_write'],
  'place-link-suggest': ['db_read'],
  'place-unlink': ['db_read', 'db_write'],
  'places-audit': ['db_read'],
  'places-by-type': ['db_read'],
  'places-candidates': ['db_read'],
  'places-dedup': ['db_read', 'db_write', 'pd_direct'],
  'places-export': ['db_read'],
  'places-geocode': ['db_read', 'db_write', 'net_out'],
  'places-no-track-census': ['db_read'],
  'places-routes-census': ['db_read'],
  'places-unmerge': ['db_read', 'db_write'],
  'prod-errors': ['db_read'],
  'prospect-scan': ['net_out', 'pd_direct'],
  'relief-coverage': ['db_read'],
  'relief-sanity': ['db_read'],
  'repo-scan': ['db_read', 'db_write', 'net_out'],
  'rescue': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'retrieval-probe': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'route-core': ['db_read'],
  'route-core-ocr-peek': ['db_read'],
  'route-core-sources': ['db_read', 'pd_direct'],
  'route-corpus': ['db_read'],
  'route-data-audit': ['db_read'],
  'route-desc-census': ['db_read', 'db_write', 'net_out', 'ai'],
  'route-desc-read': ['db_read'],
  'route-endpoints': ['db_read', 'db_write', 'net_out', 'ai'],
  'route-escalation': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'route-family-merge': ['db_read', 'db_write'],
  'route-fields-backfill': ['db_read'],
  'route-geometry-census': ['db_read'],
  'route-kind-classify': ['db_read'],
  'route-lay': ['db_read', 'db_write', 'pd_direct'],
  'route-lay-census': ['db_read'],
  'route-link-suggest': ['db_read'],
  'route-links-repair': ['db_read', 'db_write'],
  'route-place-twins': ['db_read'],
  'route-popularity': ['db_read'],
  'route-sanity-census': ['db_read'],
  'route-title-census': ['db_read'],
  'route-translit-census': ['db_read', 'db_write'],
  'route-twins-enrich': ['db_read', 'db_write'],
  'route-twins-hide': ['db_read', 'db_write'],
  'route-web-null': ['db_read', 'db_write'],
  'routes-audit': ['db_read'],
  'routes-cache-refresh': ['db_read', 'db_write', 'net_out', 'ai'],
  'routes-dedup': ['db_read', 'db_write', 'pd_direct'],
  'routes-unmerge': ['db_read', 'db_write'],
  'safety-alert': ['db_read', 'db_write'],
  'safety-check': ['db_read', 'db_write'],
  'safety-ingest': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'safety-ledger-check': ['db_read', 'db_write'],
  'schema-audit': ['db_read'],
  'schema-drift': ['db_read', 'db_write'],
  'schema-registry-census': ['db_read'],
  'schema-snapshot': ['db_read', 'db_write'],
  'scout': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'scout-diagnose': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'scout-digest': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'scout-relay-check': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'scout-study': ['db_read', 'db_write', 'net_out', 'ai'],
  'smart-notify': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'sos-census': ['db_read', 'pd_direct'],
  'sos-events-bridge': ['db_read', 'db_write'],
  'source-probe': ['net_out'],
  'sql-shape-check': ['db_read', 'db_write'],
  'ssr-sentinel': ['net_out', 'telegram', 'pd_direct'],
  'support-escalate': ['db_read', 'db_write', 'net_out', 'telegram'],
  'telegram-webhook-watchdog': ['db_read', 'db_write', 'net_out', 'telegram', 'ai'],
  'tochka-check': ['net_out'],
  'tour-describe': ['db_read', 'db_write'],
  'tour-photos': ['db_read', 'db_write'],
  'tour-photos-census': ['db_read', 'net_out'],
  'tour-pickup': ['db_read', 'db_write'],
  'tour-reminder': ['db_read', 'db_write', 'net_out', 'telegram', 'ai', 'pd_direct'],
  'tour-review-request': ['db_read', 'db_write', 'net_out', 'telegram', 'pd_direct'],
  'tour-tracks-census': ['db_read'],
  'track-attachment-audit': ['db_read', 'db_write'],
  'track-import-queue': ['db_read', 'db_write', 'net_out'],
  'trip-reminders': ['db_read', 'net_out', 'telegram', 'pd_direct'],
  'verdict-census': ['db_read'],
  'volcano-merge-gate': ['db_read', 'db_write', 'net_out', 'telegram'],
  'watchdog': ['db_read', 'db_write', 'net_out', 'telegram', 'money'],
  'waypoint-proposals': ['db_read'],
  'web-routes-census': ['db_read'],
};
